# fly.toml app configuration file generated for nanite-bot on 2023-06-18T12:54:42-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nanite-bot"
primary_region = "scl"
kill_signal = "SIGINT"
kill_timeout = "5s"
